language: haxe

sudo: false

addons:
  apt:
    packages:
      - gcc-multilib
      - g++-multilib

matrix:
  include:
    - haxe: "3.2.1"
    - haxe: "development"
      install:
        - haxelib git hxcpp https://github.com/HaxeFoundation/hxcpp.git
        - pushd $(haxelib path hxcpp | head -1)
        - pushd tools/hxcpp && haxe compile.hxml && popd
        - pushd project && neko build.n && popd
        - popd
        - yes | haxelib install nme
        - yes | haxelib install lime
        - yes | haxelib install openfl
  allow_failures:
    - haxe: "development"

install:
  - yes | haxelib install hxcpp
  - yes | haxelib install nme
  - yes | haxelib install lime
  - yes | haxelib install openfl
  - haxelib list

script:
  - haxe -cp src -main test.Test -lib nme --remap flash:nme -cpp bin                             && ./bin/Test
  - haxe -cp src -main test.Test -lib nme --remap flash:nme -neko bin/Test.n                     && neko bin/Test.n
  - haxe -cp src -main test.Test -lib openfl -lib lime --remap flash:openfl -cpp bin             && ./bin/Test
  - haxe -cp src -main test.Test -lib openfl -lib lime --remap flash:openfl -neko bin/Test.n     && neko bin/Test.n
